### ISSUE TITLE
Npm package is outdated

### ISSUE THREAD

**Issue by webartistse** [labd/nextjs-basic-auth-middleware#25]
The npm package is out dated. Any chance to update to current version?

**Comment by happylolonly** [comment]
yes, have also issue, that looks like you fixed in last commits
@blurrah @jordie23 

<img width="758" alt="image" src="https://user-images.githubusercontent.com/18665326/187482559-d32d0b81-6e21-4ea6-a76f-bff85d088c8e.png">

**Comment by blurrah** [comment]
Missed the original message, I am currently not able to work on this (holiday) and the new implementation is already broken since the stable middleware changes. Will try to pick it up next week and see if I can get a version out that works with the stable release.

**Comment by webartistse** [comment]
Nextjs middleware has a breaking change, you cannot return repsonse body in the middleware itself.

**Comment by blurrah** [comment]
I have fixed the new response issue and released the 1.0 version. Only downside I currently see to this approach is that it will endlessly keep asking for basic auth password instead of showing a 401 page if you cancel it. Nothing too bad though. Let me know in separate issues if you run into other things.
